on:
  push:
    branches:
      - master
jobs:
  test_metadata_job:
    runs-on: self-hosted
    name: Instance Metadata
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: NPM Install
        run: npm ci
      - name: Run Script
        run: node index.js
      # - name: Instance Metadata
      #   id: audit
      #   uses: nmcginn/runner-metadata@v1.0
